services:
  nginx:
    build: .
    container_name: nginx_proxy
    ports:
    - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - boraimpactar2

networks:
  boraimpactar2:
    driver: bridge